### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by ZeroCool22** [dfaker/df#1]
Microsoft Windows [Versión 10.0.16299.98]
(c) 2017 Microsoft Corporation. Todos los derechos reservados.

C:\WINDOWS\system32>cd C:\df-master

C:\df-master>python train.py
running
loading data/A: 100%|███████████████████████████████████████████████████████████████| 190/190 [00:00<00:00, 445.43it/s]
loading data/B: 100%|█████████████████████████████████████████████████████████████| 946/946 [00:00<00:00, 18816.39it/s]
Images A (125, 256, 256, 4)
Images B (0,)
Traceback (most recent call last):
  File "train.py", line 34, in <module>
    images_A[:,:,:3] += images_B[:,:,:3].mean( axis=(0,1,2) ) - images_A[:,:,:3].mean( axis=(0,1,2) )
IndexError: too many indices for array

C:\df-master>

**Comment by dfaker** [comment]
Images B appears to have zero elements in it, are you certain you copied the correct images and alignments.json into the B folder?

**Comment by dfaker** [comment]
Please see the readme for examples of the expected directory structuring.
