### ISSUE TITLE
KeyError: 'unexpected key "state_dict" in state_dict'

### ISSUE THREAD

**Issue by ZeroCool22** [dfaker/df#11]
Tried to find a solution but i couldn't get one...

![screenshot_12](https://user-images.githubusercontent.com/13344308/36062126-b56a9c66-0e44-11e8-95ec-a2f36c1fa804.png)

![screenshot_5](https://user-images.githubusercontent.com/13344308/36062316-ed972b0a-0e48-11e8-96f2-46f55638bc1a.png)

Need to change something there or...?

**Comment by dfaker** [comment]
Looks like that was a recent error in face alignment: https://github.com/1adrianb/face-alignment/issues/44
the suggested solution was to re-clone the repo.

**Comment by ZeroCool22** [comment]
I just DOWNLOADED and replaced the files with the last 1adrianb/face-alignment and still have the same error.

**Comment by dfaker** [comment]
Try deleting the downloaded FAN network from C:\Users\%USERNAME%\AppData\Local\face_alignment\data other than that I have nothing to suggest, this is all inside the face_alignment library.

**Comment by ZeroCool22** [comment]
Thx for the answer, but i tried that and it stay downloading it forever:

![screenshot_6](https://user-images.githubusercontent.com/13344308/36063305-d875b15e-0e59-11e8-9010-609b30eccbc1.png)

**Comment by ZeroCool22** [comment]
Ok, i let it end and say can't find the input files:

![can t find input files](https://user-images.githubusercontent.com/13344308/36063378-d6ea83ea-0e5a-11e8-8379-cf8fc19275dc.png)

**Comment by dfaker** [comment]
you may need to use the --file-type=png parameter if your images are stored in that format.

**Comment by ZeroCool22** [comment]
lol this was because the images were in PNG?

I convert them to JPG with ACDSee and no more problem, **they got ALIGNED!**

Now let me ask you something, isn't PNG better than JPG, because PNG is a **lossless** format?

**Comment by dfaker** [comment]
That is perfectly true, but has little relevance when you're jamming thousands through an autoencoder.
In future you'd be wise to use the file-type flag and the script will detect them without conversion.

**Comment by ZeroCool22** [comment]
Thx for the help! :)
