### ISSUE TITLE
Installing face-alignment in Windows

### ISSUE THREAD

**Issue by ghost** [dfaker/df#14]
How are others getting the face-alignment dependency to install under Windows 10? I've tried anaconda/miniconda, and the torch dependency fails during setup. I haven't been able to successfully build torch in Windows myself or get a working install independently. From looking at other people's screenshots, it looks like they are not bothering to install face-alignment?

**Comment by ZeroCool22** [comment]
Jusr extract 1adrianb/face-alignment on **dfaker root folder**.

**Comment by ghost** [comment]
@ZeroCool22 Don't you still need to enter the directory and run "python setup.py install"?

C:\df
C:\df\face-alignment
C:\df\keras-contrib

This is what you mean by root folder? Then, to install them we need to enter keras-contrib and run setup.py (which works fine)? And the same with face-alignment (which fails on torch)? I've also tried dumping the contents of face-alignment directly into C:\df in case I am misinterpreting, but that generates "missing torch" errors, which brings me back to the original issue.

I must be misinterpreting something obvious...

**Comment by ZeroCool22** [comment]
![screenshot_14](https://user-images.githubusercontent.com/13344308/36160342-b400c68e-10bf-11e8-8b32-02c78494b6b9.png)

**Comment by ghost** [comment]
@ZeroCool22 Thanks.

So I understand that you pulled the files from each git directly on top of df-master, as GUIDELINES.md is from the keras-contrib git root, and tox.ini is from the face-alignment git root, and both coexist in df-master. This is a bit weird, but I tried this. I also tried putting the underscore (not hyphen) named subfolders keras_contrib and face_alignment into the df-master root. With and without running each setup.py. And every combinations thereof. When I run align_images_masked.py, I still get "No module named 'torch'".

Also, I think the original directions in the README may have a typo:

cd into the folder df and clone https://github.com/keras-team/keras-contrib.git
make sure that the folder keras_contrib is in the root of the df respository
cd into the folder df and clone https://github.com/1adrianb/face-alignment.git
make sure that the folder face-alignment is in the root of the df respository

The underscore (_) and hyphen (-) are used 5 times in the above paragraph, but I believe either the third or fifth instance may be a typo?

In any case, I cannot get align_masked_image.py to run in Windows. train.py still runs, but then I can't merge them back together properly since the alignment is missing.

I don't understand how the face-alignment calls are being made, especially with CUDA support, without pytorch.

EDIT: I saw from your other issues screenshots that you somehow have torch already installed...

**Comment by dfaker** [comment]
Actually I think I got all the underscores and hyphens correct.

For pytorch I used anaconda and https://anaconda.org/peterjc123/pytorch 

`conda install -c peterjc123 pytorch`

**Comment by ghost** [comment]
@dfaker @ZeroCool22 
Thanks everyone. I got it working with some slight tweaks on a fresh conda install. Maybe some conflicts between global and env packages.

Full face training looks beautiful.
