### ISSUE TITLE
Kernel and Blur size, doesn't seems to change...

### ISSUE THREAD

**Issue by ZeroCool22** [dfaker/df#16]
I changed the values inside to **merge_faces_larger.py**

```
parser.add_argument( "--blurSize",          type=int, default='250' )
parser.add_argument( "--erosionKernelSize", type=int, default='170' )
```
_(Like do with the APP 1.1)_

But it doesn't make any change, how i can reduce the **surface size** of the **"fake"** face i'm adding over the original face?

**Comment by dfaker** [comment]
Correct, those parameters are currently not used. The mask is wholly based on the output of the network.

**Comment by ZeroCool22** [comment]
So how i can reduce the size, i mean not the size, the coverage area of the fake face?

What values i need to tweak and where?
