### ISSUE TITLE
Why not last TENSORFLOW in requirements.txt?

### ISSUE THREAD

**Issue by ZeroCool22** [dfaker/df#24]
tensorflow-gpu==**1.4.0** in requirements.txt

It's not compatible?

**Comment by dfaker** [comment]
I haven't tested it, I can confirm 1.4.0 and 1.3.0 both work.

I have no reason whatsoever to suspect incompatibility.

**Comment by ZeroCool22** [comment]
Using the last version of TS give us some advantage (training times, better usage of the GPU resources, or..?), or it will be almost the same?

**Comment by dfaker** [comment]
I haven't tested it and so have no profiling numbers to offer.
