### ISSUE TITLE
Why not utilize blur/kernel size

### ISSUE THREAD

**Issue by HelpSeeker** [dfaker/df#31]
I'm just curious why you don't utilize blur/kernel size settings during the merging process. Opencv's seamlessClone can produce decent results, but in my experience it leads to flickering faces more often than not and isn't concealing the boundary of the output face as effectively as the right blur/kernel size settings.

**Comment by fuzun** [comment]
There is also color mismatch & bigger face problem (Loss not 0 around the face). Altering with blur / kernel settings may improve quality when dealing with these kind of issues.

**Comment by dfaker** [comment]
Yes, I wrote the original face masking and blurring implementations.
I never saw it as important to implement in this version but if I find some time I may patch it back in.
