### ISSUE TITLE
Need for alignments.json during training

### ISSUE THREAD

**Issue by Picslook** [dfaker/df#34]
If you attempt to run train.py without having alignments.json files on both A and B folders, the training process will not be allowed to execute. I know that other implementations of this software, such as FakeApp, don't require this file for training, but I am not sure if it is necessary for this particular implementation. If it is not, it would be great if this requirement could be removed on a future version since adding more images for training would, to my knowledge, require you to run the whole extraction process again on all images.

**Comment by dfaker** [comment]
The alignments.json is essential to the training process and cannot be removed, or at the very least that data has to be available in some format.
