### ISSUE TITLE
 the converted image is the same as the previous one.

### ISSUE THREAD

**Issue by Tian-YS** [dfaker/df#51]
after train the model ,i get the 'encoder.h5' 'decoder_A.h5' 'decoder_B.h5'
when i use these file to run 'merge_face_larger.py'
the input  dir is data/B:
 ├─merged
 │   │ alignments.json
 │   │ trainingimageB1.jpg
 │   │ trainingimageB2.jpg

output dir is data/B/merged.
But the converted image is the same as the previous one.

**Comment by Tian-YS** [comment]
And i debug the merge_face_larger.py 
input the follow images. i see the foreimage is black , backimage is the dst image. 
![trump](https://user-images.githubusercontent.com/44202506/113861316-a6f98580-97d9-11eb-984b-ab88b4d8a20e.png)

**Comment by dfaker** [comment]
I suspect insufficient training or a bad dataset, since it's producing a black mask image it means it'll pass through everything from the original frame.
