### ISSUE TITLE
Images in input folder not being detected

### ISSUE THREAD

**Issue by salre9501** [dfaker/df#6]
I am running  align_images_masked.py but when I enter "python align_images_masked.py sourceA" I get the message below:            

(df) C:\df>python align_images_masked.py sourceA aligned
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa
Traceback (most recent call last):
File "align_images_masked.py", line 125, in <module>
main( parser.parse_args() )
File "align_images_masked.py", line 68, in main
assert len( input_files ) < 0, "Can't find input files"
AssertionError: Can't find input files

sourceA is where my images are stored and there are 100 of them. I've tried converting them to png, jpg, and bmp. Every time the script says it can't find the input files, but it does create an empty aligned folder in sourceA, so I know it's partly working. I am using windows 10 x64 and anaconda. My files are setup like this:

C:/df/sourceA <------100 images in here

The script is located here: C:/df/align_images_masked.py

**Comment by dfaker** [comment]
align_images_masked minimally only takes a single parameter, what's the "aligned" for?

**Comment by salre9501** [comment]
I managed to get it work by using this command:

python align_images_masked.py --file-type png sourceA aligned alignments.json

aligned is the output folder for the aligned images. It looks like I had to choose the file type to make it work. Training also works, but it looks like my GTX 1070 doesn't have enough memory. Are there any adjustments I can make when running the script?

**Comment by dfaker** [comment]
Seemingly in that case they were all in png whereas the default is to expect .jpegs
