### ISSUE TITLE
ImportError: No module named face_alignment

### ISSUE THREAD

**Issue by shadowzoom** [dfaker/df#8]
First question, does df need python2 or python3?
And when i'm trying to run python align_images_masked.py or python3 align_images_masked.py
I'm getting 

**python3 align_images_masked.py**
```
Traceback (most recent call last):
  File "align_images_masked.py", line 11, in <module>
    from face_alignment import FaceAlignment, LandmarksType
ImportError: No module named face_alignment
```
Tried to install face_alignment module, but
**pip3 install face_alignment**
```
Collecting face_alignment
  Could not find a version that satisfies the requirement face_alignment (from versions: )
No matching distribution found for face_alignment
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

```
How i can install face_alignment module? p.s. im on Ubuntu 16.04

**Comment by dfaker** [comment]
It's python 3.
You can clone face alignment from https://github.com/1adrianb/face-alignment

**Comment by shadowzoom** [comment]
Thanks mate! :)
