### ISSUE TITLE
align_images_masked.py assert input_dir.is_dir()

### ISSUE THREAD

**Issue by shadowzoom** [dfaker/df#9]
I'm trying to prepare images for train, but getting error with align_images_masked.py
**python3 align_images_masked.py input_dir=/home/tuw/Desktop/df/dp2**
```
Traceback (most recent call last):
  File "align_images_masked.py", line 125, in <module>
    main( parser.parse_args() )
  File "align_images_masked.py", line 53, in main
    assert input_dir.is_dir()
AssertionError
```
When i change line #112 from `parser.add_argument( "input_dir"  , type=str )
`
to
`parser.add_argument( "input_dir"  , type=str, nargs='?', default='/home/tuw/Desktop/df/dp2' )`It worked
How to fix it? Edit every time source code is for input dir is :weary:

**Comment by dfaker** [comment]
Either /home/tuw/Desktop/df/dp2 doesn't exist or it's not a folder, are you sure your path is correct?
Those lines aren't really designed for editing, those are designed to capture arguments at the command line like:
     align_images_masked.py /home/tuw/Desktop/df/dp2
